# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('knights_email', models.EmailField(max_length=254, unique=True)),
                ('preferred_email', models.EmailField(max_length=254, unique=True)),
                ('paid_dues', models.BooleanField(default=False)),
                ('shirt_size', models.CharField(max_length=3)),
                ('shirt_gender', models.CharField(max_length=1)),
                ('json', models.TextField()),
            ],
        ),
    ]
